version: '3'

# docker-compose build (1x only if you edit the Dockerfile or files used by it)
# docker-compose up    (everytime you wanna start the pipeline)
# docker-compose down  (everytime you wanna stop the pipeline and remove (!) containers; otherwise: Ctrl + C)

services:                               # a list of all containers you intend to use
     tweet_collector:                    # 2) run tweet_collector - container
        build: tweet_collector/         # look for a Dockerfile here -> creates an image
        volumes: 
        - ./tweet_collector/:/app/      # creating local dir "tweet_collector" into the "/app"-dir in this container
        depends_on:                     # we need to have a DB first, into which tweets are written
        - mongodb
        #env_file:
        #- .env
        
     mongodb:                            # 1) fire up MongoDB - container
        image: mongo                    # image downloaded from Docker Hub
        ports:
        - 27018:27017                   # maps port 2017 of this container (RS) to port 2017 of localhost (LS)
    
     etl_job:                          # 4) run etl_job - container
         build: etl_job/               # look for a Dockerfile here -> creates an image
         volumes:
         - ./etl_job/:/app/            # creating local dir "etl_job" into the "/app"-dir in this container
         depends_on:
         - mongodb                     # we need to have a DB first, from which we extract tweets
         - postgresdb                  # we need to have a DB first, into which we load transformed tweets
    
     postgresdb:                       # 3) fire up MongoDB - container; # name : also the hostname
         image: postgres               # image downloaded from Docker Hub
         ports:
         - 5555:5432                 # maps port 5432 of this container (RS) to port 5555 of localhost (LS)
         environment:                  # sets environment variables
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=1234
         - POSTGRES_DB=tweets
    
     slackbot:                         # finally, and the cherry on top: slackbot - container
         build: slackbot/
         volumes:
         - ./slackbot/:/app/
         depends_on:
         - postgresdb
